Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 100

Layout/LineLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  Max: 8