spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/hackaton'
    username: 'postgres'
    password: 'admin'

springdoc:
  swagger-ui:
    path: '/api'

stankin:
  api: "https://rinh-api.kovalev.team"
