spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/hackaton'
    username: 'postgres'
    password: 'admin'

  liquibase:
    enabled: 'true'

#springdoc:
#  swagger-ui:
#    path: '/api'